DUPLICATE TARGET DATABASE
  FOR STANDBY
  DORECOVER
  SPFILE
    SET db_unique_name='stdby' COMMENT 'Is standby'
    set db_domain='us.oracle.com'
    SET LOG_ARCHIVE_DEST_2='SERVICE=orcl12c ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=orcl12c'
    SET FAL_SERVER='orcl12c' COMMENT 'Is primary'
    SET DB_FILE_NAME_CONVERT='DATA/ORCL12C/','DATA/STDBY/'
    SET LOG_FILE_NAME_CONVERT='DATA/ORCL12C/','DATA/STDBY/'
  NOFILENAMECHECK;


