set linesize 80

SELECT 
   B.LHSEQ SEQUENCE#, 
   B.LHTSM FROMTIME, 
   A.LHTSM TOTIME,
   ((TO_DATE(A.LHTSM,'MM/DD/RR HH24:MI:SS') -
   TO_DATE(B.LHTSM,'MM/DD/RR HH24:MI:SS')) * 1440) MINUTES_TO_APPLY
FROM 
   X$KCCLH A, X$KCCLH B
WHERE 
   A.LHRID = B.LHRID + 1
ORDER BY 
  A.LHRID;
